# Generated by Django 5.1.1 on 2024-10-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'Employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='Company_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
